### ISSUE TITLE
[Suggestion] Add a ignore list for the block detector

### ISSUE THREAD

**Issue by wormzjl** [maruohon/autoverse#12]
By ignore I mean the block detector will pass through these blocks like they are air blocks without sending out other items, this will allow it to detect things (like ores behind stones) more efficiently.

**Comment by maruohon** [comment]
Do you mean an ignore list in the config file, or a configuration sequence in the machine?

I'm a bit hesitant to add new configuration sequence to any machines, as it would break any existing contraptions if they rely on re-programming. And other than that, I'm once again running out of GUI space in the Detector to even do that... 🤔 Personally I also don't really like detecting things through blocks.

**Comment by wormzjl** [comment]
The best solution will be a sequence, yeah...Think this is some sort of x-ray.
There might be a way to prevent existing systems from breaking while adding new sequences? Probably make it the last sequence

**Comment by maruohon** [comment]
Actually one solution would be to simply have a toggle option for going through any non-matching blocks, instead of having a specific ignore list. That option could be set by the Programmable Block Placer, or toggled by a GUI button. This also wouldn't break any existing contraptions, as it would be an additional optional programming parameter for the Programmable Block Placer when placing a Detector.

One thing about this though would be how to then handle the "other items" buffer. Should it send out an item if it didn't find any matches through blocks, but it still saw *some* other blocks?
