### ISSUE TITLE
Disabling Machine Frame causes the game to crash on start

### ISSUE THREAD

**Issue by Skyshayde** [maruohon/autoverse#13]
If you disable the machine frame Minecraft will crash on start.  I'm pretty sure its an error with the crafting recipe.  A crash log can be found at https://paste.dimdev.org/ajifizuqut.mccrash.  I'm using version 1.1.1.

**Comment by maruohon** [comment]
I don't remember if it's possible to check for multiple items to exist as a precondition in a JSON recipe, I'll have to check that... But is there a good reason to completely disable that block anyway, instead of just removing the recipe with CraftTweaker or whatever? The item/block disable options can cause various issues (as evidenced by this crash), so it might be better for me to just remove those options completely...
