### ISSUE TITLE
Issue with (pulsed) barrels and crafter

### ISSUE THREAD

**Issue by Bartz24** [maruohon/autoverse#2]
![barrel](https://user-images.githubusercontent.com/18143350/28892122-d0674ec4-779a-11e7-92c2-4477857d3d16.PNG)
As you can see, the pulsed barrel ignores stack limit for items with special limits

![crafter](https://user-images.githubusercontent.com/18143350/28892165-f5c8ae2e-779a-11e7-8f96-16507722f4bc.PNG)
Also, the crafter seems to fill up the crafting grid when the out slot is full, and then it won't use up the items in the crafting grid.

**Comment by maruohon** [comment]
Oh right, yeah, I didn't change that part of the inventory code when I copied it from Ender Utilities... SO since the barrel allows custom stack size (ie. larger than the normal maximum), that currently applies for all item. In your opinion, at least non-stackable items should not stack inside the barrels? How about stackable items that have a max stack size < 64 (like Eggs or Ender Pearls)? Should they still stack to the barrel's max?

And I'll have to take a look at the Crafter...

**Comment by Bartz24** [comment]
Hmm....I know the limit on ender pearls/eggs/snowballs is dumb, so yeah, I would agree to only have the lower limit to apply to non-stackable items

**Comment by maruohon** [comment]
These have now been fixed in version 1.0.1
